AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Transforms images by applying blur of a configured radius
Resources:
  transform:
    Type: AWS::Serverless::Function
    Properties:
      Description: Transforms images by applying blur of a configured radius
      Handler: src/index.handler
      Runtime: nodejs18.x
      CodeUri: package.zip
      MemorySize: 1536
      Policies:
        - S3ReadPolicy:
            BucketName:
              Ref: sourceBucket
        - S3CrudPolicy:
            BucketName:
              Ref: destBucket
      Timeout: 300
      Events:
        upload:
          Type: S3
          Properties:
            Bucket:
              Ref: source
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          DEST_BUCKET:
            Ref: destBucket
          BLUR_RADIUS:
            Ref: blurRadius
  source:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: sourceBucket
Parameters:
  sourceBucket:
    Type: String
    Description: Name of the S3 Bucket to read source images from (must NOT exist prior to deployment)
  destBucket:
    Type: String
    Description: Name of the S3 Bucket to put transformed images into (must exist prior to deployment)
  blurRadius:
    Type: Number
    Description: Pixel radius of the blur to apply
    Default: 10
