AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Transforms images by applying sepia tone
Resources:
  transform:
    Type: AWS::Serverless::Function
    Properties:
      Description: Transforms images by applying sepia tone
      Handler: bundle.handler
      Runtime: nodejs18.x
      CodeUri: bundle.js
      MemorySize: 1536
      Policies:
        - S3ReadPolicy:
            BucketName:
              Ref: sourceBucket
        - S3WritePolicy:
            BucketName:
              Ref: destBucket
      Timeout: 300
      Events:
        upload:
          Type: S3
          Properties:
            Bucket:
              Ref: source
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          DEST_BUCKET:
            Ref: destBucket
  source:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: sourceBucket
Parameters:
  sourceBucket:
    Type: String
    Description: Name of the S3 Bucket to read source images from (must NOT exist prior to deployment)
  destBucket:
    Type: String
    Description: Name of the S3 Bucket to put transformed images into (must exist prior to deployment)
